# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspiration',
            options={'permissions': (('can_change_inspiration', '可以修改激励语录'), ('can_add_inspiration', '可以添加激励语录'), ('can_change_inspiration_status', '可以修改激励语录状态')), 'verbose_name': '激励语录', 'verbose_name_plural': '激励语录'},
        ),
    ]
