# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0002_auto_20190820_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('passage_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('passage_author', models.CharField(max_length=36, verbose_name='文章作者')),
                ('passage_content', models.CharField(max_length=512, verbose_name='文章内容')),
                ('passage_type', models.CharField(max_length=12, verbose_name='文章类型')),
                ('passage_collect_status', models.BooleanField(default=False, verbose_name='收藏状态')),
                ('passage_picture', models.CharField(max_length=256, verbose_name='文章图片')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏人')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
