# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 04:24
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='passage_type',
        ),
        migrations.AlterField(
            model_name='passage',
            name='passage_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='passage/%Y%m%d/', verbose_name='文章图片'),
        ),
    ]
