# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20190823_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=16, verbose_name='电影名')),
                ('movie_time', models.DateTimeField(auto_now_add=True, verbose_name='上映时间')),
                ('movie_actor', models.CharField(max_length=36, verbose_name='演员')),
                ('movie_desc', models.CharField(max_length=512, verbose_name='电影简介')),
                ('movie_type', models.CharField(max_length=32, verbose_name='电影类型')),
                ('movie_picture', models.ImageField(upload_to='movie/%Y%m%d/', verbose_name='电影图片')),
                ('movie_source', models.CharField(max_length=512, verbose_name='电影资源')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
